name: Publish index.html to prod
on:
  workflow_dispatch:

jobs:
   upload_files:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.4
    - name: Upload files
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localPath: './index.html'
        remotePath: './'
